name:                HakyllSite
version:             0.1.0.0
license:             BSD3
author:              "Tilde Rose"
maintainer:          "t1lde@protonmail.com"
copyright:           "2020 Tilde Rose"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Personal Site

dependencies:
- mtl
- http-client
- http-types
- aeson
- deriving-aeson
- http-client-tls
- bytestring
- text
- exceptions
- time
- filepath

ghc-options:
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -XEmptyCase
    - -XInstanceSigs
    - -XLambdaCase
    - -XMultiWayIf
    - -XNamedFieldPuns
    - -XTupleSections
    - -XBangPatterns
    - -XKindSignatures
    - -XTypeOperators
    - -XOverloadedStrings
    - -XScopedTypeVariables
    - -XTypeApplications
    - -XApplicativeDo
    - -XDeriveGeneric
    - -XDataKinds
    - -XDerivingVia
    - -XRecordWildCards
    - -XDeriveFunctor
    - -XDeriveTraversable
    - -XOverloadedLabels
    - -XFlexibleInstances
    - -XFlexibleContexts
    - -XMultiParamTypeClasses
    - -XGADTs
    - -XTypeFamilies
    - -XAllowAmbiguousTypes
    - -XConstraintKinds
    - -XStandaloneDeriving
    - -XPolyKinds
    - -XFunctionalDependencies
    - -XRankNTypes
    - -XViewPatterns

library:
  source-dirs: src
  dependencies:
    - name: base
      version: ">= 4.7 && < 5"
      mixin: &base-mixin
        - hiding (Prelude)
    - name: relude
      mixin: &relude-mixin
        - (Relude as Prelude)

executables:
  GenDiscogsListData:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HakyllSite
    - name: base
      version: ">= 4.7 && <5"
      mixin: *base-mixin
    - name: relude
      mixin: *relude-mixin
  site:
    main:                Site.hs
    source-dirs:         site/src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HakyllSite
    - name: base
      version: ">= 4.7 && <5"
      mixin: *base-mixin
    - name: relude
      mixin: *relude-mixin
    - hakyll
    - pandoc
