name:                HakyllSite
version:             0.1.0.0
license:             BSD3
author:              "Tilde Rose"
maintainer:          "t1lde@protonmail.com"
copyright:           "2020 Tilde Rose"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Personal Site

dependencies:
- mtl
- http-client
- http-types
- aeson
- deriving-aeson
- http-client-tls
- bytestring
- text
- exceptions
- time
- filepath
- binary
- bifunctors

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -XEmptyCase
    - -XInstanceSigs
    - -XLambdaCase
    - -XMultiWayIf
    - -XNamedFieldPuns
    - -XTupleSections
    - -XBangPatterns
    - -XKindSignatures
    - -XTypeOperators
    - -XOverloadedStrings
    - -XScopedTypeVariables
    - -XTypeApplications
    - -XApplicativeDo
    - -XDeriveGeneric
    - -XDataKinds
    - -XDerivingVia
    - -XRecordWildCards
    - -XDeriveFunctor
    - -XDeriveTraversable
    - -XOverloadedLabels
    - -XFlexibleInstances
    - -XFlexibleContexts
    - -XMultiParamTypeClasses
    - -XGADTs
    - -XTypeFamilies
    - -XAllowAmbiguousTypes
    - -XConstraintKinds
    - -XStandaloneDeriving
    - -XPolyKinds
    - -XFunctionalDependencies
    - -XRankNTypes
    - -XViewPatterns
    - -XOverloadedLabels

executables:
  site:
    main:                Site.hs
    source-dirs:         site/src
    ghc-options:
      - -O0
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - name: base
        version: ">= 4.7 && < 5"
        mixin:
          - hiding (Prelude)
      - name: relude
        mixin:
          - (Relude as Prelude, Relude.Extra.Foldable1, Relude.Extra.Type, Relude.Extra.Newtype, Relude.Extra.Map)
      - hakyll
      - pandoc
